services:
  database:
    image: 'postgres:latest'
    container_name: books_online_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_online_db
    networks:
      - bo-network


  rabbitmq:
    image: rabbitmq:management
    container_name: books_online_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./init_rabbitmq.sh:/init_rabbitmq.sh
    networks:
      - bo-network
  redis:
    image: redis:7.4-alpine
    container_name: books_online_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    networks:
      - bo-network
  backend:
    build: .
    container_name: books_online_backend
    ports:
      - "8000:8000"
    depends_on:
      - database
      - rabbitmq
      - redis
    command: poetry run start
    networks:
      - bo-network

  worker:
    build: .
    container_name: books_online_worker
    depends_on:
      - backend
      - rabbitmq
      - redis
    command: .venv/bin/celery -A books_online.orders.tasks worker --loglevel=info
    networks:
      - bo-network

  frontend:
    build: ./webapp
    container_name: books_online_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - bo-network

networks:
  bo-network:
    driver: bridge
